######################################################################
# Automatically generated by qmake (3.0) Tue Jul 10 20:28:37 2018
######################################################################

TEMPLATE = app
TARGET = santak2
INCLUDEPATH += .

QT += gui
QT += widgets

# Input
HEADERS += SantakWindow.h
SOURCES += SantakWindow.cpp main.cpp
